### ISSUE TITLE
Errors During Package Building

### ISSUE THREAD

**Issue by Nashobahomma** [TBooker/PicMin#1]
Hello,

We are interested in using PicMin for some analyses of genetic variation across geographic distances. We are running into some issues with building the package for use on our data, however. In particular, the issues we are facing now are arising from R code in the vignette. In the code chunk from lines 327-399, we have several errors:

- `object 'alpha_a' not found`
- `'x' must be atomic`

How would we work around these issues to get a compiled vignette document?

Thank you,
Amber Nashoba and Tom Kono (konox006 [at] umn.edu)

**Comment by TBooker** [comment]
Thanks, this was due a version issue with a previous version of the method. 

It should be working well now if you pull the current version.
